import { type ViewStyle, type TextStyle } from 'react-native';

export const entryEditorStyles = {
  container: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  backdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(24, 19, 14, 0.24)',
  },
  editorPage: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(139, 115, 85, 0.08)',
  },
  headerButton: {
    minWidth: 48,
    paddingVertical: 6,
  },
  headerButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#8A7C70',
  },
  headerSaveText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6A89CC',
    textAlign: 'right',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3D342E',
  },
  main: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 220,
    gap: 16,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  typeText: {
    fontSize: 13,
    fontWeight: '600',
  },
  contentSurface: {
    minHeight: 420,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(139, 115, 85, 0.14)',
    backgroundColor: '#FFFDF9',
    shadowColor: '#5A4330',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
    elevation: 1,
  },
  surfaceLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#A08F82',
    marginBottom: 14,
  },
  contentInput: {
    minHeight: 340,
    fontSize: 18,
    lineHeight: 32,
    color: '#2F241E',
    letterSpacing: 0.15,
    padding: 0,
  },
  metaSection: {
    gap: 6,
    paddingHorizontal: 4,
  },
  metaLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#A08F82',
    letterSpacing: 0.6,
  },
  metaValue: {
    fontSize: 14,
    color: '#6B5B4D',
  },
  tagDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(139, 115, 85, 0.10)',
    gap: 12,
  },
  tagDockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tagDockTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4A4A4A',
  },
  tagDockCount: {
    fontSize: 12,
    color: '#A08F82',
  },
  commonTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commonChip: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F4F0FF',
    borderWidth: 1,
    borderColor: '#E2DAF8',
  },
  commonChipSelected: {
    backgroundColor: '#A491D3',
    borderColor: '#A491D3',
  },
  commonChipText: {
    fontSize: 13,
    color: '#6A5ACD',
  },
  commonChipTextSelected: {
    color: '#FFFFFF',
  },
  tagsInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(139, 115, 85, 0.12)',
    backgroundColor: '#FFFDF9',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#4A4A4A',
  },
  tagsPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#F7F2EA',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(139, 115, 85, 0.10)',
  },
  tagChipText: {
    fontSize: 13,
    color: '#7A6758',
    fontWeight: '500',
  },
  suggestionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F7F4FF',
    borderWidth: 1,
    borderColor: '#E6DFF8',
  },
  suggestionChipText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#8F7AC8',
  },
} satisfies Record<string, ViewStyle | TextStyle>;
