import { StyleSheet } from 'react-native';

export const sidebarStyles = StyleSheet.create({
  sidebar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 10,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F1F4',
    gap: 12,
  },
  headerTextGroup: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#4A4A4A',
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#8F95A3',
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  menuList: {
    flex: 1,
    paddingTop: 12,
    paddingHorizontal: 12,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginVertical: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EDF0F5',
    backgroundColor: '#FAFBFD',
  },
  menuIconContainer: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F4F8',
    borderRadius: 10,
    marginRight: 12,
  },
  menuContent: {
    flex: 1,
    paddingTop: 1,
  },
  menuText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3E4656',
  },
  menuDescription: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    color: '#8C94A4',
  },
  menuChevronContainer: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E6EE',
    marginVertical: 10,
    marginHorizontal: 12,
  },
  footer: {
    padding: 20,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E5E5',
    backgroundColor: '#FFFFFF',
  },
  versionText: {
    fontSize: 12,
    color: '#A3A3A3',
  },
});
