import { StyleSheet } from 'react-native';

export const entryCardStyles = StyleSheet.create({
  syncStatusBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  syncStatusPill: {
    position: 'absolute',
    top: 12,
    right: 42,
    zIndex: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.94)',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  syncStatusPillText: {
    fontSize: 11,
    color: '#666666',
    fontWeight: '600',
  },
  cardShadow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 115, 85, 0.15)',
    elevation: 0,
  },
  calendarCardShadow: {
    borderRadius: 10,
    borderColor: 'rgba(139, 115, 85, 0.06)',
    shadowColor: '#5A4330',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 1,
  },
  cardContainer: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  calendarCardShell: {
    borderRadius: 10,
  },
  calendarCardContainer: {
    borderRadius: 10,
  },
  content: {
    padding: 20,
    gap: 12,
  },
  calendarContent: {
    padding: 0,
    gap: 0,
  },
  contentText: {
    borderRadius: 12,
  },
  contentPhoto: {
    padding: 0,
    gap: 0,
  },
  contentVoice: {
    padding: 0,
  },
  textContent: {
    fontSize: 16,
    lineHeight: 28,
    color: '#1A1A1A',
    letterSpacing: 0.3,
  },
  photoCaption: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#525252',
  },
  calendarKickerText: {
    fontSize: 11,
    letterSpacing: 1.2,
    color: '#8B76C8',
    marginBottom: 10,
    fontWeight: '700',
  },
  calendarKickerPhoto: {
    fontSize: 11,
    letterSpacing: 1.2,
    color: '#8A7E70',
    marginBottom: 8,
    fontWeight: '700',
  },
  calendarKickerVoice: {
    fontSize: 11,
    letterSpacing: 1.2,
    color: '#B28646',
    marginBottom: 10,
    fontWeight: '700',
  },
  calendarTextCard: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  calendarTextContent: {
    fontSize: 17,
    lineHeight: 29,
    color: '#3F374B',
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  calendarPhotoCard: {
    padding: 0,
  },
  calendarPhotoBodyWrap: {
    position: 'relative',
  },
  calendarPhotoCountOverlay: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: 'rgba(0,0,0,0.38)',
  },
  calendarPhotoMeta: {
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  calendarPhotoCountText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  calendarPhotoCaption: {
    fontSize: 14,
    lineHeight: 22,
    color: '#67584B',
  },
  calendarPhotoEmptyState: {
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FBF7F1',
    borderWidth: 1,
    borderColor: '#E7DDD0',
    borderStyle: 'dashed',
    paddingHorizontal: 24,
  },
  calendarPhotoEmptyBadge: {
    width: 56,
    height: 56,
    borderRadius: 6,
    backgroundColor: '#ECE1D5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  calendarSinglePhoto: {
    width: '100%',
    borderRadius: 6,
    backgroundColor: '#ECE7E0',
  },
  calendarPhotoMultiWrap: {
    flexDirection: 'row',
    gap: 6,
  },
  calendarPhotoDoubleWrap: {
    flexDirection: 'row',
    gap: 3,
  },
  calendarPhotoDoubleCell: {
    flex: 1,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#ECE7E0',
  },
  calendarPhotoPrimary: {
    flex: 1.35,
    borderRadius: 6,
    overflow: 'hidden',
  },
  calendarPhotoSecondaryColumn: {
    flex: 0.75,
    gap: 6,
  },
  calendarPhotoSecondaryCell: {
    flex: 1,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#ECE7E0',
  },
  calendarPhotoImage: {
    width: '100%',
    height: '100%',
  },
  calendarPhotoOverflowMask: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  calendarPhotoOverflowText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
  },
  calendarTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  calendarPhotoTagsContainer: {
    marginTop: 10,
  },
  calendarTag: {
    backgroundColor: '#FFFCF7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#EAE0D5',
  },
  calendarTagTextTone: {
    borderColor: '#E2D7F0',
    backgroundColor: '#FFFCF7',
  },
  calendarTagVoiceTone: {
    borderColor: '#EFDDBE',
    backgroundColor: '#FFFCF7',
  },
  calendarTagText: {
    fontSize: 12,
    color: '#7E7486',
    fontWeight: '500',
  },
  calendarTagTextTextTone: {
    color: '#7D69B8',
  },
  calendarTagTextVoiceTone: {
    color: '#9A7D55',
  },
  calendarMoreTagsHint: {
    fontSize: 12,
    color: '#A3968A',
    alignSelf: 'center',
  },
  calendarTranscriptionContainer: {
    marginTop: 12,
    borderRadius: 6,
    backgroundColor: '#FBF7F1',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#ECE2D7',
  },
  calendarTranscriptionText: {
    fontSize: 13,
    lineHeight: 21,
    color: '#64594F',
  },
  tag: {
    backgroundColor: '#F9731620',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#F97316',
  },
  tagText: {
    fontSize: 12,
    color: '#EA580C',
    fontWeight: '500',
  },
  moreTagsHint: {
    fontSize: 12,
    color: '#A3A3A3',
    alignSelf: 'center',
  },
  transcriptionContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  transcriptionLabel: {
    fontSize: 11,
    color: '#737373',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  transcriptionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#525252',
  },
  expandHint: {
    fontSize: 12,
    color: '#A3A3A3',
    textAlign: 'center',
    paddingTop: 8,
    paddingBottom: 4,
  },
  recordingContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
  },
  recordingCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  recordingCenter: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  waveformCompact: {
    width: '100%',
    height: 28,
  },
  recordingLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#8E8E93',
    marginTop: 4,
  },
  recordingTimeCompact: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    fontVariant: ['tabular-nums'],
    minWidth: 60,
    textAlign: 'right',
  },
  stopButtonCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F5A68D',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F5A68D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  stopIconCompact: {
    width: 16,
    height: 16,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  playButtonCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F5A623',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  voicePlayContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
  },
  voicePlayCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  voiceWaveformCompact: {
    flex: 1,
    height: 28,
  },
  voiceTimeCompact: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    fontVariant: ['tabular-nums'],
    minWidth: 60,
    textAlign: 'right',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  photoTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 14,
    paddingTop: 0,
    paddingBottom: 12,
  },
  voiceCard: {
    padding: 16,
    gap: 14,
    borderRadius: 12,
  },
  voicePlayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  voicePlayBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F5A623',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 5,
  },
  voicePlayBtnDisabled: {
    opacity: 0.7,
  },
  voiceWaveform: {
    flex: 1,
    height: 32,
  },
  voiceDuration: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8E8E93',
    fontVariant: ['tabular-nums'],
    minWidth: 38,
    textAlign: 'right',
  },
  voiceUploadingText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#B0822F',
    minWidth: 58,
    textAlign: 'right',
  },
  voiceCaption: {
    fontSize: 15,
    lineHeight: 24,
    color: '#1A1A1A',
    letterSpacing: 0.2,
  },
  audioMissingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  audioMissingText: {
    fontSize: 13,
    color: '#A3A3A3',
  },
  calendarVoiceCard: {
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  calendarVoiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 1,
  },
  calendarVoicePlayBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#F2A62A',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F2A62A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  calendarVoiceTrack: {
    flex: 1,
  },
  calendarVoiceTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  calendarVoiceTrackActive: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  calendarVoiceHint: {
    fontSize: 11,
    color: '#9C8260',
  },
  calendarVoiceTime: {
    fontSize: 11,
    fontWeight: '600',
    color: '#A4865C',
    fontVariant: ['tabular-nums'],
    minWidth: 34,
    textAlign: 'right',
  },
  calendarVoiceCaption: {
    marginTop: 10,
    fontSize: 13,
    lineHeight: 20,
    color: '#8B735B',
  },
  calendarRecordingCard: {
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  calendarRecordingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 2,
  },
  calendarStopButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#EEAE78',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EEAE78',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
});
