import { StyleSheet } from 'react-native';

export const voiceRecorderStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 12,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5E5E5',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFF8EE',
    borderRadius: 10,
  },
  typeBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#F5A623',
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    paddingVertical: 24,
    alignItems: 'center',
    minHeight: 180,
    justifyContent: 'center',
  },
  idleContainer: {
    alignItems: 'center',
    gap: 12,
  },
  micCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#FFF8EE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  idleTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  idleSubtitle: {
    fontSize: 14,
    color: '#A3A3A3',
  },
  recordingContainer: {
    alignItems: 'center',
    gap: 16,
    width: '100%',
  },
  timer: {
    fontSize: 52,
    fontWeight: '700',
    color: '#1A1A1A',
    fontVariant: ['tabular-nums'],
    letterSpacing: 2,
  },
  waveformBox: {
    width: '100%',
    height: 28,
  },
  recordingHint: {
    fontSize: 13,
    color: '#A3A3A3',
    fontWeight: '500',
  },
  doneContainer: {
    alignItems: 'center',
    gap: 12,
  },
  doneCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  doneTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  doneDuration: {
    fontSize: 16,
    color: '#737373',
    fontVariant: ['tabular-nums'],
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  primaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F5A623',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  stopBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#EF4444',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  secondaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F5F5F5',
  },
  primaryBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  secondaryBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A4A4A',
  },
  stopIcon: {
    width: 14,
    height: 14,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  btnDisabled: {
    opacity: 0.5,
  },
  bottomSpacer: {
    height: 24,
  },
});
